### PR TITLE
Fix typo in French translation

### PR DESCRIPTION
**Pull request by Hywan**
Note to the reviewer: I am a native French speaker (and grammar nazi too).

### CODE REVIEW

**Comment by Hywan** [comment]
Do you need to fully translate the app to French?

**Comment by andrenatal** [comment]
Thanks @Hywan! Yes, we need full translation to French.

**Comment by jedireza** [comment]
:tada: :+1:

**Comment by Hywan** [comment]
@andrenatal Is the reference file this one: https://github.com/mozilla/vaani/blob/master/src/localization/en-US.l20n?

**Pull request merged**
