### PR TITLE
added audio alert on begin and end of recognition

### PR DESCRIPTION
**Pull request by andrenatal**
@jedireza probably we'll need to change the exact moment where hark starts listen to prevent it to react from the beep sound, but this is minor.

### CODE REVIEW

**Comment by jedireza** [comment]
I think we should rename these files so they don't contain the word `camcorder`.

**Comment by andrenatal** [comment]
@jedireza sure, thanks you. I changed them.

**Comment by jedireza** [comment]
I'm not sure `speech` is accurate either. Your variable names are good. How about we follow suit with the file names?
- `alert_start.opus`
- `alert_end.opus`

**Comment by andrenatal** [comment]
@jedireza ok, changed again..

**Comment by jedireza** [comment]
Thanks. Sorry for being so picky :grin:

**Pull request merged**
