### PR TITLE
Improve _onVolumeChange animations

### PR DESCRIPTION
**Pull request by pivanov**

### CODE REVIEW

**Comment by pivanov** [comment]
@jedireza this is the best way for now with the animations ... ~20-30 fps

**Comment by jedireza** [comment]
When using this I don't see animations on my custom desktop build or on a Flame. I did not try an Aries yet.

**Comment by pivanov** [comment]
Huh sorry ... my fault ... PR is updated

**Comment by jedireza** [comment]
Thanks @pivanov! The performance on:
- the desktop is great.
- on the Flame is better than the previous round, however I usually don't see more than 2 rings showing at a time.
- on the Aries, it seems a little less appealing than the last PR.

Do you have an Aries and a Flame on hand?

**Comment by pivanov** [comment]
I will have Flame tomorrow morning and I will test it again

**Comment by pivanov** [comment]
@jedireza I think now we have best result. Can you check?

**Comment by jedireza** [comment]
I tested again and it seems like the dots are showing/hiding in reverse now. With silence they are always showing and as the volume is louder the rings hide from outside to inside.

**Comment by jedireza** [comment]
I just tested again with the latest changes and still seeing the reverse behavior like I mentioned above.

**Comment by pivanov** [comment]
I think is correct now :)

**Comment by jedireza** [comment]
Thanks!! The animations look great.

**Pull request merged**
